version: "3.9"
services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: "psql_hn"
      POSTGRES_USER: "psql_hn"
      POSTGRES_PASSWORD: "psql_hn"
    ports:
      - "5432:5432"
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
