spring:
  application:
    name: fun
  cassandra:
    contact-points: 127.0.0.1
    keyspace-name: dt
    local-datacenter: datacenter1
    port: 9042

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

  metrics:
    export:
      prometheus:
        enabled: true

  observations:
    annotations:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

logging:
  config: classpath:logback.xml
